/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package autoreport;

import static autoreport.ExcellReport.PorcentagemErro;
import static autoreport.ExcellReport.Services;
import static autoreport.ExcellReport.SheetGenerator;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author aalonso
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser2 = new javax.swing.JFileChooser();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser3 = new javax.swing.JFileChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jFileChooser2.setCurrentDirectory(new java.io.File("C:\\PAYPAL\\PROJETOS\\VIVO\\Monthly Reports"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nome do  Report (Período):");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField1.setText("Exemplo: Dezembro-2013");
        jTextField1.setName("reportName"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("REPORT CONSOLIDATE");

        jTextField2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField2.setText("C:\\PAYPAL\\PROJETOS\\VIVO\\Monthly Reports\\Consolidado\\");
            jTextField2.setName("reportName"); // NOI18N
            jTextField2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField2ActionPerformed(evt);
                }
            });

            jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel3.setText("Output da planilha:");

            jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel4.setText("Activate PIN Service:");

            jTextField3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField3.setText("File Location...");
            jTextField3.setName("reportName"); // NOI18N
            jTextField3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField3ActionPerformed(evt);
                }
            });

            jButton1.setText("Selecionar Arquivo");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            jLabel5.setText("SERVICES");

            jTextField4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField4.setText("File Location...");
            jTextField4.setName("reportName"); // NOI18N
            jTextField4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField4ActionPerformed(evt);
                }
            });

            jButton2.setText("Selecionar Arquivo");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel6.setText("AddCard Service");

            jTextField5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField5.setText("File Location...");
            jTextField5.setName("reportName"); // NOI18N
            jTextField5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField5ActionPerformed(evt);
                }
            });

            jButton3.setText("Selecionar Arquivo");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel7.setText("Delink Service");

            jTextField6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField6.setText("File Location...");
            jTextField6.setName("reportName"); // NOI18N
            jTextField6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField6ActionPerformed(evt);
                }
            });

            jButton4.setText("Selecionar Arquivo");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel8.setText("RequestPayment Service");

            jTextField7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField7.setText("File Location...");
            jTextField7.setName("reportName"); // NOI18N
            jTextField7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField7ActionPerformed(evt);
                }
            });

            jButton5.setText("Selecionar Arquivo");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel9.setText("ResetPIN Service:");

            jTextField8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField8.setText("File Location...");
            jTextField8.setName("reportName"); // NOI18N
            jTextField8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField8ActionPerformed(evt);
                }
            });

            jButton6.setText("Selecionar Arquivo");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel10.setText("SendPayment Service:");

            jTextField9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField9.setText("File Location...");
            jTextField9.setName("reportName"); // NOI18N
            jTextField9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField9ActionPerformed(evt);
                }
            });

            jButton7.setText("Selecionar Arquivo");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });

            jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel11.setText("SignUp Service:");

            jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            jLabel12.setText("TOPUP");

            jTextField10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField10.setText("File Location...");
            jTextField10.setName("reportName"); // NOI18N
            jTextField10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField10ActionPerformed(evt);
                }
            });

            jTextField11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField11.setText("File Location...");
            jTextField11.setName("reportName"); // NOI18N
            jTextField11.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField11ActionPerformed(evt);
                }
            });

            jButton8.setText("Selecionar Arquivo");
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
                }
            });

            jButton9.setText("Selecionar Arquivo");
            jButton9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton9ActionPerformed(evt);
                }
            });

            jButton10.setText("Selecionar Arquivo");
            jButton10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton10ActionPerformed(evt);
                }
            });

            jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel13.setText("VivoWeb En:");

            jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel14.setText("Facebook PP Web:");

            jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel15.setText("VivoWeb Es:");

            jButton11.setText("Selecionar Arquivo");
            jButton11.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton11ActionPerformed(evt);
                }
            });

            jTextField12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField12.setText("File Location...");
            jTextField12.setName("reportName"); // NOI18N
            jTextField12.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField12ActionPerformed(evt);
                }
            });

            jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel16.setText("Facebook Vivo Web:");

            jTextField13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField13.setText("File Location...");
            jTextField13.setName("reportName"); // NOI18N
            jTextField13.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField13ActionPerformed(evt);
                }
            });

            jButton12.setText("Selecionar Arquivo");
            jButton12.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton12ActionPerformed(evt);
                }
            });

            jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel17.setText("Selecao Premiada Web:");

            jTextField14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField14.setText("File Location...");
            jTextField14.setName("reportName"); // NOI18N
            jTextField14.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField14ActionPerformed(evt);
                }
            });

            jButton13.setText("Selecionar Arquivo");
            jButton13.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton13ActionPerformed(evt);
                }
            });

            jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel18.setText("USSD Mobile:");

            jTextField15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField15.setText("File Location...");
            jTextField15.setName("reportName"); // NOI18N
            jTextField15.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField15ActionPerformed(evt);
                }
            });

            jButton14.setText("Selecionar Arquivo");
            jButton14.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton14ActionPerformed(evt);
                }
            });

            jTextField16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField16.setText("File Location...");
            jTextField16.setName("reportName"); // NOI18N
            jTextField16.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField16ActionPerformed(evt);
                }
            });

            jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel19.setText("VivoWeb Web:");

            jTextField17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jTextField17.setText("File Location...");
            jTextField17.setName("reportName"); // NOI18N
            jTextField17.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jTextField17ActionPerformed(evt);
                }
            });

            jButton15.setText("Selecionar Arquivo");
            jButton15.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton15ActionPerformed(evt);
                }
            });

            jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
            jLabel20.setText("VivoWeb Pt_Intl:");

            jButton16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
            jButton16.setText("Gerar Relatório");
            jButton16.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton16ActionPerformed(evt);
                }
            });

            helpMenu.setMnemonic('h');

            contentsMenuItem.setMnemonic('c');
            contentsMenuItem.setText("Contents");
            helpMenu.add(contentsMenuItem);

            aboutMenuItem.setMnemonic('a');
            aboutMenuItem.setText("About");
            helpMenu.add(aboutMenuItem);

            menuBar.add(helpMenu);

            jMenu1.setText("Menu");

            jMenuItem1.setText("Sair");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem1);

            menuBar.add(jMenu1);

            setJMenuBar(menuBar);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addGap(268, 268, 268))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField8))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField7))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField6))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField5))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField10))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField16))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField11))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField12))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField13))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField14))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField15)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton9)
                                                        .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addComponent(jSeparator1)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel2))
                    .addGap(31, 31, 31)
                    .addComponent(jButton16)
                    .addGap(305, 305, 305))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton12))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton15)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jButton16)))
                    .addContainerGap(24, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField3.setText(temp);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField4.setText(temp);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField5.setText(temp);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField6.setText(temp);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField7.setText(temp);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField8.setText(temp);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField9.setText(temp);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField11.setText(temp);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField12.setText(temp);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField13.setText(temp);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField14.setText(temp);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField15.setText(temp);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField16.setText(temp);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField10.setText(temp);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         jFileChooser2.showOpenDialog(null);
         String temp = jFileChooser2.getSelectedFile().getPath();
         jTextField17.setText(temp);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        //Abre WorkSheet
        if(jTextField1.getText().equals("Exemplo: Dezembro-2013")){
        JOptionPane.showMessageDialog(rootPane, "Insira um nome de arquivo válido.","Erro", 0);
        return;
        }else{
                if(jTextField3.getText().equals("File Location...") ||
                        jTextField4.getText().equals("File Location...") ||
                        jTextField5.getText().equals("File Location...") ||
                        jTextField6.getText().equals("File Location...") ||
                        jTextField7.getText().equals("File Location...") ||
                        jTextField8.getText().equals("File Location...") ||
                        jTextField9.getText().equals("File Location...") ||
                        jTextField10.getText().equals("File Location...") ||
                        jTextField11.getText().equals("File Location...") ||
                        jTextField12.getText().equals("File Location...") ||
                        jTextField13.getText().equals("File Location...") ||
                        jTextField14.getText().equals("File Location...") ||
                        jTextField15.getText().equals("File Location...") ||
                        jTextField16.getText().equals("File Location...") ||
                        jTextField17.getText().equals("File Location..."))
                {
                    
                    JOptionPane.showMessageDialog(rootPane, "Especifique a localização de cada report.","Tente novamente", 2);
                    return;
                
                }
        }
        
        String sheetName = jTextField1.getText();
        String Data = "";
        HSSFWorkbook workbook = new HSSFWorkbook();
        HSSFSheet sheet = workbook.createSheet("Errors Report VIVO "+sheetName);
        
        //Inicia Leitura de pdfs e cria padrão de dados
            float perct;
            //Activate PIN Service Report
            System.out.println("-----------------------------------------------");
            perct = PorcentagemErro(jTextField3.getText());
            System.out.println("Activate PIN Service Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data = "Activate PIN Service-"+perct+"#" +Services(jTextField3.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //AddCard Service Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField4.getText());
            System.out.println("AddCard Service Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%AddCard Service-"+perct+"#" +Services(jTextField4.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //Delink Service Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField5.getText());
            System.out.println("Delink Service Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%Delink Service-"+perct+"#"+Services(jTextField5.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //RequestPayment Service Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField6.getText());
            System.out.println("RequestPayment Service Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%RequestPayment Service-"+perct+"#"+Services(jTextField6.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //ResetPIN Service Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField7.getText());
            System.out.println("ResetPIN Service Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%ResetPIN Service-"+perct+"#"+Services(jTextField7.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //SendPayment Service Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField8.getText());
            System.out.println("SendPayment Service Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%SendPayment Service-"+perct+"#"+Services(jTextField8.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //SignUp Service Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField9.getText());
            System.out.println("SignUp Service Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%SignUp Service-"+perct+"#"+Services(jTextField9.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //Facebook PP Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField11.getText());
            System.out.println("Facebook PP Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%Facebook PP Topup-"+perct+"#" +Services(jTextField11.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //Facebook VIVO Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField12.getText());
            System.out.println("Facebook VIVO Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%Facebook VIVO Topup-"+perct+"#" +Services(jTextField12.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //VivoWebPtIntl Web Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField13.getText());
            System.out.println("Selecao Premiada Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%Selecao Premiada Web Topup-"+perct+"#" +Services(jTextField13.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //USSD Mobile Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField14.getText());
            System.out.println("USSD Mobile Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%USSD Mobile Topup-"+perct+"#" +Services(jTextField14.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //VivoWeb Web Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField15.getText());
            System.out.println("VivoWeb Web Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%VivoWeb Web Topup-"+perct+"#" +Services(jTextField15.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //VivoWebEn Web Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField16.getText());
            System.out.println("VivoWebEn Web Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%VivoWebEn Web Topup-"+perct+"#" +Services(jTextField16.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //VivoWebEs Web Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField10.getText());
            System.out.println("VivoWebEs Web Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%VivoWebEs Web Topup-"+perct+"#" +Services(jTextField10.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
            //VivoWebPtIntl Web Topup Report
            System.out.println("-----------------------------------------------");
            perct=PorcentagemErro(jTextField17.getText());
            System.out.println("VivoWebPtIntl Web Topup Report: "+perct);
            System.out.println("-----------------------------------------------");
            Data += "%VivoWebPtIntl Web Topup-"+perct+"#" +Services(jTextField17.getText());
            System.out.println("_______________________________________________\n");
            System.out.println("\n");
            
           
           
            System.out.println(Data);
            
            SheetGenerator(Data,sheetName,sheet,workbook);
            
            try {
                FileOutputStream out = new FileOutputStream(new File(jTextField2.getText()+"Error Report Consolidado "+sheetName+".xls"));
                workbook.write(out);
                out.close();
                JOptionPane.showMessageDialog(rootPane, "Consolidação bem sucedida.","Sucesso", 3);

            } catch (FileNotFoundException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Falha na consolidação.","Error", 0);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Falha na consolidação.","Error", 0);
            }
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFileChooser jFileChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
